# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
