# fly.toml app configuration file generated for book-finder on 2024-12-01T17:09:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'book-finder'
primary_region = 'lhr'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "data"
  destination = "/app/storage"

[deploy]
  release_command = "bundle exec rails db:prepare"

[env]
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_LOG_LEVEL = "debug"
